# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-10 05:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='proyecto_picture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='proyecto.Proyecto'),
        ),
    ]
