# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-24 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='donate_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='num_likes',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
