# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-22 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_auto_20170610_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='donate',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
