# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-28 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0004_auto_20170527_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='Logos/'),
        ),
    ]
