# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-09 20:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0005_auto_20170528_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='galeria_imagenes',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='publicacion',
        ),
        migrations.DeleteModel(
            name='Galeria',
        ),
    ]
