# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-29 04:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0008_auto_20170529_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='proyecto',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='proyecto.proyecto'),
        ),
    ]
