# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-10 02:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0006_auto_20170609_1603'),
        ('proyecto', '0009_auto_20170529_0042'),
    ]

    operations = [
    ]
