# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-28 22:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tipo_usuario',
            field=models.CharField(choices=[('COLABORADOR', 'Colaborador'), ('ESTUDIANTE', 'Estudiante')], default=django.utils.timezone.now, max_length=2),
            preserve_default=False,
        ),
    ]
