# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-23 23:39
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoPaypal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(db_index=True, max_length=64)),
                ('payer_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('payer_email', models.EmailField(blank=True, max_length=254)),
                ('donate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('pagado', models.BooleanField(default=False)),
                ('Proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.Proyecto')),
            ],
        ),
    ]
