# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-18 18:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion_general', models.CharField(max_length=200)),
                ('descripcion_detallada', models.CharField(max_length=1500)),
                ('definicion_problema', models.CharField(max_length=1500)),
                ('definicion_solucion', models.CharField(max_length=1500)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
