# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-19 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion_imagen', models.CharField(max_length=500)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='media/Galeria/')),
            ],
        ),
        migrations.AddField(
            model_name='proyecto',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/Logos/'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='publicacion',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='galeria_imagenes',
            field=models.ManyToManyField(blank=True, to='proyecto.Galeria'),
        ),
    ]
