# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-19 18:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_auto_20170519_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='publicacion',
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
