# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-24 00:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0004_auto_20170523_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='publicacion',
        ),
    ]
