# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-25 05:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyecto', '0005_remove_proyecto_publicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='definicion_problema',
            field=models.TextField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='definicion_solucion',
            field=models.TextField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='descripcion_detallada',
            field=models.TextField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='descripcion_general',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='comment',
            name='post_comment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='proyecto.proyecto'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_comment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
